### ISSUE TITLE
Send email, SMPT connection?

### ISSUE THREAD

**Issue by nowitz** [aleksandar888/cordova-plugin-imap#3]
Hi, is there a way to send an email using the plugin?
Thanks

**Comment by aleksandar888** [comment]
[Imap.zip](https://github.com/aleksandar888/cordova-plugin-imap/files/10299270/Imap.zip)
[index.zip](https://github.com/aleksandar888/cordova-plugin-imap/files/10299271/index.zip)


Hi,

This plugin doesn't include a feature for sending email messages. 
I plan to publish a new plugin that will offer SMTP features. Until then, you can follow the below description and try to add the SMTP feature on this plugin.

Download the Imap.zip file.
1. Copy the method named "sendMessage" and all of its components from the files:  for Android:  "Imap.java", for iOS: "Imap.h" and "Imap.m". This should be added to the Codrova plugin.
2. Copy the method signature from this file "Imap.js" located here: "\Imap\www". This should be added to the Cordova plugin.
3. If you are using the plugin on IONIC. Copy the components of the sendMessage method from the "index.ts (index.zip) file, to the plugin wrapper located here: myApp\node_modules\@awesome-cordova-plugins\imap\ngx\index.js

In you need more details feel free to contact me.
